# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "${custom.planmode}$directory$git_state$git_branch$git_metrics$character"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = "$branch(:$remote_branch) "

[git_metrics]
disabled = false

[custom.planmode]
command = "cat ~/.config/.plan_mode 2>/dev/null | awk '{print substr($0, 0, 1)}'"
when = "test -f ~/.config/.plan_mode"
format = "[$output]($style) "
style = "bold yellow"
