#! /bin/bash
set -e

export HOMELOCATION=$HOME/$1
export BACKUPLOCATION=./backups/$1

mkdir -p $(dirname $HOMELOCATION)
mkdir -p $(dirname $BACKUPLOCATION)

if [ -e $HOMELOCATION ] && [ ! -L $HOMELOCATION ]
then
  mv $HOMELOCATION $BACKUPLOCATION
else
  rm -rf $HOMELOCATION
fi
ln -s $(pwd)/$1 $HOMELOCATION
