theme = "sonokai"

[editor]
bufferline = "multiple"
line-number = "relative"
cursorline = true
true-color = true
idle-timeout = 300
color-modes = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = false
character = "|"

[editor.soft-wrap]
enable = true

[editor.jump-mode]
jump-keys = "ghfjdkslatyrueiwoqpbnvmcxz" # default is "jwetovxqpdygfblzhckisuranm"

[keys.normal]
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
X = "extend_line_above"
g = { t = ":tab-next" }

[keys.select]
space = { g = ["yank", ":hsplit-new", "paste_after", ":pipe xargs ag | column -t"] }
