theme = "sonokai"

[editor]
bufferline = "multiple"
line-number = "relative"
cursorline = true
true-color = true
idle-timeout = 0
color-modes = true
auto-format = true
jump-label-alphabet = "ghfjdkslaurytieowbvncmxpqz" # QWERTY home row, then top/bottom, moving out from the middle

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.lsp]
display-inlay-hints = false
display-messages = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = false
character = "|"

[editor.soft-wrap]
enable = true

[keys.normal]
"ret" = ["move_line_down", "goto_first_nonwhitespace"] # Maps the enter key to move to start of next line
X = "extend_line_above"
"space" = { c = "file_picker_in_current_buffer_directory" }
# g = { t = ":tab-next" }
C-b = ":sh gh browse %{buffer_name}:%{cursor_line} -c %sh{latest_pushed_commit}"
C-B = ":echo %sh{git blame --date=short -L %{cursor_line},+1 %{buffer_name} | sed -E 's/[0-9]+).*//' | sed 's/(//g'}"
C-k = ":sh catalyst send %{buffer_name} %{cursor_line}"

[keys.select]
space = { g = ["yank", ":hsplit-new", "paste_after", ":pipe xargs ag | column -t"] }

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["spacer", "diagnostics"]
right = ["position", "position-percentage", "file-type", "separator", "file-line-ending", "separator", "selections", "file-encoding"]
separator = "|"
