theme = "sonokai"

[editor]
bufferline = "multiple"
line-number = "relative"
cursorline = true
true-color = true
idle-timeout = 0
completion-replace = true
color-modes = true

[editor.lsp]
display-messages = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = false
character = "|"

[editor.soft-wrap]
enable = true

[keys.select]
space = { g = ["yank", ":hsplit-new", "paste_after", ":pipe xargs ag | column -t"] }
